### ISSUE TITLE
Checking SvTYPE == SVt_PV is fragile

### ISSUE THREAD

**Issue by leonerd** [team-at-cpan/Net-Async-Redis-XS#2]
https://github.com/team-at-cpan/Net-Async-Redis-XS/blob/9a29ffd20466c9c9221d99b08a94cc05848a8d7f/XS.xs#L44

The SV types for "regular scalars" are fragile and prone to expansion up towards the most generic SVt_PVMG at basically any time. E.g. given

```perl
my $x = 123;
$x = "hello";
```

The `$x` scalar was originally an `SVt_IV` and then got upgraded to something that can hold a PV, so probably `SVt_PVIV`. Even though it only currently contains a PV part, the struct type itself is PVIV.

What you want to do here is check the `SvPOK` flag, to ask "is this a regular scalar with a string part".

**Comment by tom-binary** [comment]
Yes, worth relaxing that constraint - will update.

The original reason for the direct "fail unless this is SVt_PV" is that I didn't want to deal with any cases such as "result-from-`substr`" or magic or blessed objects or similar: just a plain scalar bytestring, as part of the protocol parsing. If it started out as an IV for example then something's fundamentally wrong in the rest of the code!

**Comment by tm604** [comment]
Fixed in d027e09, released in [v0.007](https://github.com/team-at-cpan/Net-Async-Redis-XS/tree/v0.007)
