### ISSUE TITLE
strncmp is better written strnEQ

### ISSUE THREAD

**Issue by leonerd** [team-at-cpan/Net-Async-Redis-XS#3]
https://github.com/team-at-cpan/Net-Async-Redis-XS/blob/9a29ffd20466c9c9221d99b08a94cc05848a8d7f/XS.xs#L190

A tiny hint, but it's often nicer to use perl's `strnEQ` macro, because it has the more expected true/false result than comparing `cmp == 0`.

**Comment by tm604** [comment]
Fixed in 57b26ba, released in [v0.007](https://github.com/team-at-cpan/Net-Async-Redis-XS/tree/v0.007)
